use_frameworks!

platform :ios, '9.0'

target 'BEEAppearance_Example' do
  pod 'BEEAppearance', :path => '../'

  target 'BEEAppearance_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

target 'BEEAppearanceSwift' do
  pod 'BEEAppearance', :path => '../'
end
